### ISSUE TITLE
FormattedNumber doesn't work with a style

### ISSUE THREAD

**Issue by cmmouritsen** [joshswan/react-native-globalize#18]
I get an error of "invalid style" when I run this sample for FormattedNumber:

```
import { FormattedNumber } from 'react-native-globalize';

class MyComponent extends Component {
  render() {
    return (
      <FormattedNumber
        value={1.5}
        minimumFractionDigits={2}
        style={{ color: 'red' }} />
    )
  }
}
```

I've tracked it down to these two lines of code: https://github.com/joshswan/globalize/blob/master/src/number/pattern.js#L14
https://github.com/joshswan/globalize/blob/master/src/number.js#L83

It seems that the style property that is passed in to style the TextField is being passed to the number formatter. Am I doing something wrong? Is there a workaround for this issue?

**Comment by joshswan** [comment]
Nice catch. The root cause of the problem is (here)[https://github.com/joshswan/react-native-globalize/blob/master/lib/components/FormattedNumber.js#L18] where `this.props` in its entirety is passed to `getNumberFormatted`, which itself accepts an option called `style` for determining the number style. I'll get to work on this right away.

**Comment by joshswan** [comment]
Should be good to go on v0.9.1 which I just published to npm. Thanks for pointing this out!

**Comment by cmmouritsen** [comment]
Awesome. Thanks for the quick response.
