### ISSUE TITLE
'undefined is not an object' when using <FormattedDate>

### ISSUE THREAD

**Issue by jbwan** [joshswan/react-native-globalize#2]
Hi,

I'm new to the react-native space but I have stumbled on a problem that I cannot seem to workaround with this. When using the <FormattedDate> tag to render a simple test (I'm literally using your <FormattedDate value={new Date()} skeleton="yMMMdhm" /> example from the guide), I run into an error that complains about "undefined is not an object (evaluating 'this.context.globalize.getDateFormatter')". This is the message thrown back from a catch block I have in my render method.

The tag is being used within a class method that creates entries for a ScrollView - everything works perfectly until I try to use the FormattedDate tag. I moved the tag to be within the renderScene method that I am using to fill out the Navigator but the problem is exactly the same. It's almost as if something has dropped out of scope but the problem is not obvious to me.

I'm using v4.24 of Node, react-native 0.18.1, react-native-cli 0.1.10, and a Genymotion Android emulator configured for v6 API Level 23.

Thanks

**Comment by joshswan** [comment]
Are you using ES6 classes? If so, you need to be careful due to the lack of autobinding: https://facebook.github.io/react/docs/reusable-components.html#no-autobinding

If your method is called renderRow, just stick `this.renderRow = this.renderRow.bind(this);` in the constructor.

Let me know if that solves it.

**Comment by jbwan** [comment]
Thanks for the response. I'm creating all my classes using the React.createClass() wrapper with a provided specification. I'm a little new to this space so perhaps my understanding is not 100% but I think this means I am not using the ES6 classes and as such do not need to perform the extra bindings, constructor for state, etc. At least, I have encountered warnings in the past, from react-native, of the form "React does this for you automatically in a high performance way" when I have had bind statements in my code as I attempted to learn some examples. I'm probably doing something simple in the wrong way. I'll strip back my app later and perhaps post a bare skeleton example of the problem if that would help to identify a possible bug or perhaps me as the cause of the problem. Thanks again for your advice so far.

**Comment by joshswan** [comment]
You're right that you're not using ES6 classes if you're using `React.createClass`. I just reread your original message with that in mind and I'm pretty sure I know the problem. In order to access the message formatter functions directly through the context, you need to specify your component's contextTypes:

```javascript
var MyComponent = React.createClass({
    contextTypes: {
        globalize: React.PropTypes.object.isRequired,
    },
    // ...
});
```

You can read more about React's context here: https://facebook.github.io/react/docs/context.html. And I'll update the docs to reflect this requirement. Hope that solves the issue for you.

**Comment by jbwan** [comment]
Thanks again for the response and the information. Sadly, the issue is still prevailing for me. I stripped back a screen from my app, removed any entanglements with the Navigator component that I was using to go between screens and took it back to a minimal implementation. Both with and without the contextTypes code mentioned, I get the same error of 'undefined is not an object'. The error message on the emulator reports the innermost exception is thrown at line 53, in the render method, of FormattedDate.js, the line that reads:

```var formatDate = this.context.globalize.getDateFormatter(this.props);```

After debugging the code and stepping through the chain of calls, adding some alert statements to the FormattedDate.js file, I discovered that the context object is present but the globalize object is coming through as null. The code I am using for the cutdown example is shown below. Perhaps I am missing something, my apologies if so but I can't see why the code is failing. For a more complex example where I was using the Navigator component to render scenes, I thought perhaps you had pinpointed the problem of the context losing objects down the chain but in this code, it seems to be at the upper most level, if I understand it correctly.

```
'use strict';

var React = require('react-native');
var Dimensions = require('Dimensions');
var windowSize = Dimensions.get('window');
var RNGlobalize = require('react-native-globalize');

const config = require('./config')

var {
  AppRegistry,
  StyleSheet,
  Component,
  View,
  Text,
  TextInput,
  ListView,
  TouchableOpacity,
  Image,
  AsyncStorage
} = React;

var {
	FormattedDate
} = RNGlobalize;

var LoginScreen2 = React.createClass({
  contextTypes: {
    globalize: React.PropTypes.object.isRequired,
  },
  
  getInitialState() {
    return {
      username: '',
      password: '',
    }
  },

  render() {
    return (
      <View style={styles.container}>
        <Text><FormattedDate value={new Date()} skeleton="yMMMdhm"/></Text>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flexDirection: 'column',
    flex: 1,
    backgroundColor: 'transparent'
  }
});

module.exports = LoginScreen2;
```

**Comment by joshswan** [comment]
The globalize object needs to be added to the context using `getChildContext` on a parent component. If you read the first part of the documentation, it'll point you in the right direction. Either use the `FormattedWrapper` component at the root of your application so that all child components receive the required context object, or look at how [FormattedWrapper](https://github.com/joshswan/react-native-globalize/blob/master/src/components/FormattedWrapper.js) works and provide the context using one of your own components.

**Comment by jbwan** [comment]
Ah, ok! Thank you again so much Josh. I had a misunderstanding of how the context was passed on from component to component. I thought that by not having any custom components I did not have to pass on child context and I just couldn't see it. My apologies and gratitude for your assistance. I used the FormattedWrapper component around the root of my app and I can use the FormattedDate in a simple example now. Looks like I still have a lot of reading to do. Thank you once again for your time.
