### ISSUE TITLE
Npm install warnings with React Native 0.44

### ISSUE THREAD

**Issue by thedjinn** [joshswan/react-native-globalize#21]
When using this package with React Native 0.44 there is a warning about conflicting version numbers for the React package:

```
npm WARN react-native-globalize@1.1.0 requires a peer of react@>=14.5.0 but none was installed.
```

This probably has something to do with recent versions of React Native depending on a React 16 alpha version.

**Comment by joshswan** [comment]
You can safely ignore that warning. There's nothing conflicting and no additional versions are being installed. Once RN switches to a non-prerelease version of React instead of 16.0.0-alpha.12, the warning will go away. You'll get the same warning with many other packages (or at least I am, e.g. react-native-maps).
