### ISSUE TITLE
Way to do localization without using FormattedMessage

### ISSUE THREAD

**Issue by lucasbento** [joshswan/react-native-globalize#32]
Is there's a way to do localization programatically without using `<FormattedMessage />`?

My use case is that I receive a key and need to get a message based on it but my function is outside of React, therefore I don't have access to `context`.

I can use the [Globalize class](https://github.com/joshswan/react-native-globalize/blob/master/lib/globalize.js) but I would have to go through [all the algorithm to format it](https://github.com/joshswan/react-native-globalize/blob/master/lib/components/FormattedMessage.js#L19-L65). Perhaps it's a good option to export that algorithm as well.

**Comment by joshswan** [comment]
If you're only using basic values in the message, you can skip all the complicated parts of that and simply call `getMessageFormatter` and then format your message using the resulting function (i.e. the first and last lines of the section you highlighted). The rest of it is for handling React components as values within the message.

That said, I do agree that it could be a good idea to split the logic out of the render function so that ti's accessible outside of `FormattedMessage`. I'll try to take a look at that when I've got some time or if you want to take a stab at it, feel free :)

**Comment by lucasbento** [comment]
@joshswan: thanks for replying.

I started changing it but then realized that I was able to do what I wanted without that change:

```js
  Globalize.loadMessages(locales);

  const instance = new Globalize(defaultLanguage, 'EUR', {
    fallback: false,
    warnOnMissingMessage: false,
  });

  const messageFormatter = instance.getMessageFormatter('notifications/journalEntry');

  const localizedMessage = messageFormatter({
    user1: 'First user',
    user2: 'Second user',
  }); // Will hold "First user added a journal post for Second user"
```

Not sure if this issue is relevant anymore.

**Comment by joshswan** [comment]
Yep outside React and without using React components as values in the message, that's all you need to go. Glad you figured it out!
