### ISSUE TITLE
Fallback language?

### ISSUE THREAD

**Issue by alvinwoon** [joshswan/react-native-globalize#6]
Firstly, thanks for the wonderful module.

Is there an option to set fallback language?

Right now I am using NativeModule to determine user ios locale `NativeModules.SettingsManager.settings.AppleLocale.`

When you don't have the defined language in your message bundle, you will get error such as this with release build. For instance, I didn't set 'en_TW' for my language json but did have  'en'

`'RCTFatalException: Unhandled JS Exception: E_MISSING_MESSAGE_BUNDLE: Missing message bundle for locale `en_TW`.'`

**Comment by joshswan** [comment]
Currently there's no option for that, but it sounds like a good idea for an enhancement. Happy to accept a PR or I'll look into it when I've got a bit of time. In the meantime, you can always implement something quick using the list of locales from the docs

**Comment by joshswan** [comment]
Just published v0.7.0 to npm. There's now a `localeFallback` prop on `FormattedWrapper` that'll attempt to find an appropriate fallback if the locale you pass isn't available. In your example above `en_TW` would fall back to `en`.

There's also some new exposed methods: `availableLocales` and `localeIsLoaded`. You can read about them [here](https://github.com/joshswan/react-native-globalize/blob/master/README.md#globalize) and use them to create your own fallback implementation since the default one is pretty simple :)

**Comment by alvinwoon** [comment]
you are awesome!
