### ISSUE TITLE
Globalize compiler?

### ISSUE THREAD

**Issue by mikelambert** [joshswan/react-native-globalize#7]
I see that jquery supports a Globalize Compiler, to help build JS files that contain just the minimal bits necessary (instead of needing to embed the fat, or even semi-trimmed cldr.json). Curious if you've explored using this at all within a react-native-globalize app?

I'm trying to decide between react-intl (based on formatjs stack, many more users, tentative RN support, but doesn't appear to optimize files well like RN-G's gulpfile does?) and react-native-globalize (based on globalize stack. the RN-G project has much less users/testing than R-I, but this Globalize Compiler seems like some nice hotness to have)

**Comment by joshswan** [comment]
Originally I put together this library because I had an urgent need for message and currency formatting in RN and react-intl didn't support RN at all. If they've started to support RN, it might be time to revisit their library.

With regards to the compiler, I definitely looked into it while I was building the library, but it didn't seem like it would give any clear benefits. It was created with web usage in mind so that you wouldn't have to download the CLDR file to users' browsers, but with RN we don't really have that problem since it's included in the app bundle. Performance is the other benefit since the formatters are pre-compiled, but the measured difference between pre-compiled formatters and generate-once-then-cache as is currently implemented in RN-G was negligible. Basically I didn't see many benefits and the compiler is very limited in terms of its file-scanning abilities so it looked like it'd be a pain to set up.

Those are my thoughts. Open for a debate though :)

**Comment by mikelambert** [comment]
I was going off this thread for react-intl support for RN: https://github.com/yahoo/react-intl/issues/119

It supports a <FormattedMessage>, or you can write your own component wrappers that call intl.formatMessage() (where intl is injected into props in the same way that redux injects dispatch and redux-state props). I assume it's similar for other types of formatting.

As far as RN-G and G-compiler, the thought of an 8MB file (which would 90% of my app size) simply for date/time formatting sounds ridiculous, not to mention makes load/compilation time take a lot longer on the device (annoying for development, but I'm trying to make my app quick to start). The latter could be solved by storing per-language json files on disk and loading the relevant one at startup I'm sure. In my case, I've trimmed out a bunch of languages I don't have/need, which helps for now.

I'm not clear exactly what the compiler shortens to, but in theory it'd only be including the relevant bits of data for formatting dates in the couple of date formats I have, right? And save on huge amounts of the CLDR? Though you said it's very limited in its file-scanning abilities, curious if you have any more info/pointers on that?

**Comment by joshswan** [comment]
Agreed on the CLDR file size (though your PR brought it down to 5MB :) ). And yes, loading only the appropriate CLDR data at runtime would definitely speed things up. I originally wanted to dynamically load the CLDR data per-language only when needed but ran into issues with the RN packager since it didn't (doesn't?) support dynamic requires (e.g. `require('./cldr/{lang}.json')`). We could get around that by wrapping static requires in functions and only calling the functions when needed (e.g. `function loadEN() { require('./cldr/en.json'); }`, but originally, the app I built this for was pretty large and needed a bunch of languages, so I just accepted the tradeoff between startup speed and quick implementation. Implementing some sort of dynamic loading would definitely improve startup speed though.

And maybe it makes sense to only include english or a couple of languages by default instead of the huge number currently included. Then implementors can implement only what they need. That would both decrease startup time (depending on how many other languages implementors include) and decrease the included CLDR file size.

When formatting, Globalize takes the CLDR data and creates a formatting function (e.g. when you use this library and call `getCurrencyFormatter('USD')` and it returns a function. The compiler only includes those formatting functions, allowing you to leave out the CLDR data altogether. However, any time you need to change the options on a formatter or add a different one (e.g. `getCurrencyFormatter('GBP')`) you'd have to recompile. From what I see [here](https://github.com/jquery-support/globalize-compiler#extract-input-), the extraction part of the compiler can only recognize very specific statements currently, so the onus would be on this library to scan source files for necessary formatters and then pass them to the compiler. Ultimately, that would produce a great result as it would contain the absolute minimum necessary to support your app, but it seems like it'd be difficult to implement (though maybe I'm wrong :) )

**Comment by mikelambert** [comment]
RN-G uses a 5MB cldr.json. FormatJS's Intl polyfill locale data is 70KB per language, or 954KB for every language, using some string interning / js-compression (https://raw.githubusercontent.com/andyearnshaw/Intl.js/master/locale-data/complete.js), that could possibly increase load time a bit. I could probably significantly reduce their per-locale/combined files even further if I ripped out the non-gregorian calendar support.

As far as dynamic loading of files for RN-G, I'd investigate loading it with https://github.com/johanneslumpe/react-native-fs and pass it to JSON.parse (though not sure how much manual per-platform configuration that'd require to get the files on there, which could be too annoying). It would avoid any json parsing/eval/etc for un-used languages. (But yes, I currently have my own branch of RN-G that includes only my 5 languages and disables currencies, which I used to prototype my date formatting, so maybe "only" half my app source code is cldr.json now, and load speeds are fine.)

And I see what you mean about the G-C being limited to the static methods. I guess it also would mean imposing a compilation step to a RN app, which might make a real mess of any debugging or existing packager stuff. :/

**Comment by joshswan** [comment]
Intl.js gave me a lot of issues originally with RN (and it also had a ton of issues itself at the time), which was another reason I went this route.

Anyway as an experiment, I implemented a currency filter in the gulpfile, only including CAD, EUR, GBP, and USD by default and it brought the cldr.json size down to 1.96MB, so I'm guessing you could decrease your file size even more with that (currently on master). Using only these currencies each language is ~35KB, plus ~80KB for the supplemental, and I'm sure there's more optimization that can be done.

**Comment by joshswan** [comment]
And some sort of compression could be implemented on cldr.json as well, but as you said, it might increase the load time.

**Comment by ranjanse** [comment]
getting error:
Uncaught SyntaxError: Unexpected token import   index.js:8

**Comment by joshswan** [comment]
@ranjanse This library uses ES6 module syntax. The React Native packager transforms these automatically so there should be no issue unless your React Native version is very old. Check your setup, and if you're still having issues, please open a separate issue with your RN version. This issue is not related in any way.
