### ISSUE TITLE
How can I add more locales or currencies types?

### ISSUE THREAD

**Issue by sibelius** [joshswan/react-native-globalize#9]
Is there a way to customize which locales and currency I wanna support?

**Comment by joshswan** [comment]
If you simply want to add more CLDR data, you can load it as documented in the README [here](https://github.com/joshswan/react-native-globalize#formattedwrapper) and [here](https://github.com/joshswan/react-native-globalize#globalize).

Otherwise, if you want to make larger changes to which data is included, clone the repo, modify the `locales` and `currencies` arrays as desired, and run `gulp cldr`. That will produce a new `cldr.json` file in the `src` directory which you can use to replace the `cldr.json` file that's included by default.

**Comment by sibelius** [comment]
tks

**Comment by recs182** [comment]
I made what you describe above, but I getting this error
![screenshot_1488811120](https://cloud.githubusercontent.com/assets/5971123/23614395/8521cd6c-0261-11e7-936a-32b7dc27611c.png)

Any clue?

**Comment by joshswan** [comment]
Looks like your additional currency isn't being included properly. How are you adding it?

**Comment by recs182** [comment]
Considering you question I'll assume that I not adding it, how could I proceed to add it?

Thanks for answering.

**Comment by joshswan** [comment]
If you've already created a JSON file with additional CLDR data, you can load it using the `cldr` prop on `FormattedWrapper` as I stated originally: `<FormattedWrapper cldr={[require('path/to/file.json')]}>`.

Otherwise, my recommendation would be to just fork the repo, tweak the currencies and locales in `gulpfile.js` to your liking, run `gulp cldr` and commit the resulting `cldr.json` and install your fork.

**Comment by recs182** [comment]
Ok, thanks man, I'll do it! Very helpfull!
